#! /usr/bin/env node

'use strict'
var path = require('path')
var _ = require('lodash')

var currentPath = path.resolve("./")
var splittedPath = currentPath.split(path.sep)
splittedPath = _.pull(splittedPath, '')

console.log(splittedPath)
console.log(splittedPath.length)
